### ISSUE TITLE
Issue with Piston and Tilt removed terms

### ISSUE THREAD

**Issue by 3beckjr** [3beckjr/Summer_2017_Work#1]
The piston and tilt removed variants of the equation are orders of magnitude off and the shape is similarly weird.  I think it's somewhere in the A0 and A1 terms.

**Comment by jpbos** [comment]
Take a look at the paper. One or the other of the functions uses the generalized hypergeometric function not just the HypergeometricPFQ function. This is called out in the paper as an overbar on the F. I'm not saying that is the issue but it gives you something to look at.

**Comment by 3beckjr** [comment]
That brought the graphs closer to what they should be, but not quite.

 I think it has something to do with the A0 and A1 terms, but I've triple checked those. It looks like the function is the right size/ shape, it's just been shifted down by 27 for piston and tilt removed case and 203 for the piston removed case. 

I also tried the eqn 34 variant of Y(S) and it didn't end up yield anything on the output.
